-- MySQL Script generated by MySQL Workbench
-- Tue Jan 28 16:26:56 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema bibliotheque-microservice
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema bibliotheque-microservice
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `bibliotheque-microservice` DEFAULT CHARACTER SET utf8 ;
USE `bibliotheque-microservice` ;

-- -----------------------------------------------------
-- Table `bibliotheque-microservice`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bibliotheque-microservice`.`user` (
  `id_user` INT NOT NULL AUTO_INCREMENT,
  `firstname` VARCHAR(30) NOT NULL,
  `lastname` VARCHAR(30) NOT NULL,
  `email` VARCHAR(255) NOT NULL,
  `password` VARCHAR(255) NOT NULL,
  `active` TINYINT NOT NULL,
  PRIMARY KEY (`id_user`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bibliotheque-microservice`.`book`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bibliotheque-microservice`.`book` (
  `id_book` INT NOT NULL AUTO_INCREMENT,
  `book_name` VARCHAR(35) NOT NULL,
  `book_author` VARCHAR(35) NOT NULL,
  `book_editor` VARCHAR(35) NOT NULL,
  PRIMARY KEY (`id_book`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bibliotheque-microservice`.`copy`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bibliotheque-microservice`.`copy` (
  `id_copy` INT NOT NULL AUTO_INCREMENT,
  `status` VARCHAR(1) NOT NULL,
  `book_id_book` INT NOT NULL,
  PRIMARY KEY (`id_copy`, `book_id_book`),
  INDEX `fk_copy_book_idx` (`book_id_book` ASC),
  CONSTRAINT `fk_copy_book`
    FOREIGN KEY (`book_id_book`)
    REFERENCES `bibliotheque-microservice`.`book` (`id_book`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bibliotheque-microservice`.`reservation`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bibliotheque-microservice`.`reservation` (
  `id_reservation` INT NOT NULL AUTO_INCREMENT,
  `date_begin` VARCHAR(10) NOT NULL,
  `date_end` VARCHAR(10) NOT NULL,
  `is_archived` TINYINT NOT NULL,
  `copy_id_copy` INT NOT NULL,
  `user_id_user` INT NOT NULL,
  PRIMARY KEY (`id_reservation`, `copy_id_copy`, `user_id_user`),
  INDEX `fk_reservation_copy1_idx` (`copy_id_copy` ASC),
  INDEX `fk_reservation_user1_idx` (`user_id_user` ASC),
  CONSTRAINT `fk_reservation_copy1`
    FOREIGN KEY (`copy_id_copy`)
    REFERENCES `bibliotheque-microservice`.`copy` (`id_copy`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_reservation_user1`
    FOREIGN KEY (`user_id_user`)
    REFERENCES `bibliotheque-microservice`.`user` (`id_user`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
